openapi: 3.0.2
info:
  description: Api Documentation for legalpost
  version: '1.2'
  title: Api Documentation
  contact: { }
servers:
  - url: "http://localhost:8888"
tags:
  - name: UserAuth
    description: UserAuth
  - name: Admin
    description: Ендпоинты для администраторов магазина
  - name: SuperAdmin
    description: SuperAdmin
  - name: User
    description: User
  - name: Product
    description: Product

paths:
  /user/login:
    post:
      description: Аутентификация пользователя
      tags:
        - UserAuth
      summary: Аутентификация пользователя
      operationId: authenticationUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDto'
      responses:
        200:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /user/registration:
    post:
      description: Регистрация пользователя
      tags:
        - UserAuth
      summary: Регистрация пользователя
      operationId: registrationUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestDto'
      responses:
        200:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /admin/add-product/{categoryName}:
    post:
      description: Добавление нового товара
      tags:
        - Admin
      summary: Добавление нового товара
      operationId: addProduct
      parameters:
        - name: categoryName
          in: path
          description: Категория товара
          required: true
          schema:
            type: string
      requestBody:
        description: Бинарное содержимое файлов
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDto'
      responses:
        200:
          description: успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /super-admin/add-category:
    post:
      description: Добавление категории товаров
      tags:
        - SuperAdmin
      summary: Добавление категории товаров
      operationId: addCategory
      requestBody:
        description: Добавление категории товаров
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDto'
      responses:
        200:
          description: успешно
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /admin/add-images:
    post:
      description: Добавление списка изображений
      tags:
        - Admin
      summary: Добавление списка изображений
      operationId: addImages
      requestBody:
        description: Бинарное содержимое файлов
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                productName:
                  description: Наименование товара
                  type: string
                images:
                  description: Список изображений товара
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: успешно
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /admin/add-image:
    post:
      description: Добавление изображения
      tags:
        - Admin
      summary: Добавление изображения
      operationId: addImage
      requestBody:
        description: Бинарное содержимое файла
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                productName:
                  description: Наименование товара
                  type: string
                image:
                  description: Изображение товара
                  type: string
                  format: binary
      responses:
        200:
          description: успешно
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /categories:
    get:
      description: Получение списка категорий
      tags:
        - User
      summary: Получение списка категорий
      operationId: getCategories
      responses:
        200:
          description: описание
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /admin/products:
    get:
      description: Получение списка товаров владельца
      tags:
        - Admin
      summary: Получение списка товаров владельца
      operationId: getProductsOwner
      responses:
        200:
          description: описание
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

  /products:
    get:
      description: Получение списка товаров
      tags:
        - Product
      summary: Получение списка товаров
      operationId: getProducts
      responses:
        200:
          description: описание
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        500:
          description: описание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      deprecated: false

components:
  schemas:
    ProductDto:
      description: ProductDto
      type: object
      properties:
        id:
          description: Идентификатор товара
          type: string
          format: uuid
        price:
          description: Цена товара
          type: integer
        name:
          description: Наименование товара
          type: string
        description:
          description: Краткое описание товара
          type: string
        fullDescription:
          description: Полное описание товара
          type: string

    CategoryDto:
      description: Категория товара
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    UserRequestDto:
      description: UserRequestDto
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    UserTokenDto:
      description: UserTokenDto
      type: object
      properties:
        token:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'

    Role:
      type: string
      enum:
        - USER
        - ADMIN
        - MANAGER

    ResultDto:
      title: ResultDto
      type: object
      properties:
        timestamp:
          type: string
          example: 2021-10-20T12:11:39.488+0000
          description: Время и дата запроса
        code:
          type: string
          example: QRPT.00000
          description: Код сервиса
        message:
          type: string
          example: OK (удачный ответ) ЮЛ найдено
          description: Системное сообщение об ошибке
        status:
          type: integer
          minLength: 3
          maxLength: 3
          example: 500
          description: Код

    ErrorResult:
      title: ErrorResult
      description: Ошибка
      type: object
      properties:
        result:
          $ref: '#/components/schemas/ResultDto'